# Generated by Django 2.1.3 on 2019-03-23 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hw2', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DATE', models.CharField(max_length=8, unique=True)),
                ('TMAX', models.FloatField(default=0)),
                ('TMIN', models.FloatField(default=0)),
            ],
            options={
                'ordering': ('DATE',),
            },
        ),
        migrations.DeleteModel(
            name='Record',
        ),
    ]
